### ISSUE TITLE
Add redis to dbms

### ISSUE THREAD

**Issue by steinkel** [LordSimal/cakephp-dsn-generator#73]
Redis would be a nice addition to the list of dbmss.

Thank you.

**Comment by LordSimal** [comment]
Please check the website if the generated REDIS DSN string is as you would expect 😉

**Comment by steinkel** [comment]
I'll check if the database number is working properly with the generated dsn.

Additionally I would add https://book.cakephp.org/5/en/core-libraries/caching.html#redisengine-options at least `persistent` and `timeout` as additional params.

I don't know if you wanted to cover the cache engines too though...

**Comment by LordSimal** [comment]
I think I will make a separate cache engine DSN form to make it easier to differentiate the 2 types of DSN strings 😁
